"""Interactive setup wizard for first-time configuration."""

from __future__ import annotations

from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm, FloatPrompt, Prompt

console = Console()


def run_wizard() -> None:
    """Run the interactive setup wizard."""
    console.print()
    console.print("[bold]Welcome to Argos Budget Guardian![/bold]")
    console.print()
    console.print("Let's configure your default settings.")
    console.print("You can change these anytime with [bold]argos config[/bold].")
    console.print()

    # Budget
    budget = FloatPrompt.ask(
        "What's your default budget per session (in USD)?",
        default=10.0,
    )

    # Action on limit
    action = Prompt.ask(
        "What should happen when the budget is reached?",
        choices=["stop", "pause", "warn"],
        default="stop",
    )

    # Warning threshold
    warn_pct = FloatPrompt.ask(
        "At what percentage should you get a warning?",
        default=80.0,
    )

    # Dashboard
    show_dashboard = Confirm.ask(
        "Show a live dashboard by default?",
        default=False,
    )

    # Persistence
    persist = Confirm.ask(
        "Save cost history to disk for later review?",
        default=True,
    )

    # Write config
    config_dir = Path.home() / ".argos-budget-guardian"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.toml"

    config_content = f"""# Argos Budget Guardian Configuration
# Generated by 'argos setup'

[budget]
default_budget_usd = {budget}
action_on_limit = "{action}"
warn_at_percent = {warn_pct}

[dashboard]
show_by_default = {str(show_dashboard).lower()}

[storage]
persist_history = {str(persist).lower()}
db_path = "{config_dir / 'history.db'}"
"""

    config_path.write_text(config_content)

    console.print()
    console.print(f"[green]Configuration saved to {config_path}[/green]")
    console.print()
    console.print("[bold]You're all set![/bold] Add this to your code:")
    console.print()
    console.print("[dim]from argos_budget_guardian import GuardedAgent[/dim]")
    console.print()
    console.print(f"[dim]async with GuardedAgent(budget={budget}) as agent:[/dim]")
    console.print('[dim]    async for msg in agent.query("your prompt"):[/dim]')
    console.print("[dim]        pass[/dim]")
    console.print()
